//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularWebApiMakeLifeEasyModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AngularWebApiMakeLifeEasyEntities : DbContext
    {
        public AngularWebApiMakeLifeEasyEntities()
            : base("name=AngularWebApiMakeLifeEasyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Band> Bands { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ProductFile> ProductFiles { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Locale> Locales { get; set; }
        public virtual DbSet<LocalesHistory> LocalesHistories { get; set; }
    }
}
