//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularWebApiMakeLifeEasyModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalesHistory
    {
        public Nullable<System.Guid> Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> LocalesHistoryId { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public decimal Longitude { get; set; }
        public Nullable<decimal> Accuracy { get; set; }
        public string Name { get; set; }
        public string DB { get; set; }
    }
}
