//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularWebApiMakeLifeEasyModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public string CustomerId { get; set; }
        public int StaffId { get; set; }
        public string Name { get; set; }
        public byte[] Icon { get; set; }
        public byte[] Logo { get; set; }
        public string Image { get; set; }
        public string Filepath { get; set; }
        public string Tags { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
    }
}
